In [2]:
import numpy as np

In [4]:
x_input = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_input = np.array([460, 232, 178])
print(x_input)

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]


In [6]:
def compute_cost(x,y,w,b):
    m = x.shape[0]
    cost = 0.0
    for i in range(m):
        f_wb_i = np.dot(x[i],w) + b
        cost = cost+ (f_wb_i - y[i])**2
    return cost/(2*m)

In [18]:
def compute_gradient(x,y,w,b):
    m,n = x.shape
    dj_dw = np.zeros((n,))
    dj_db = 0.0

    for i in range(m):
        err = np.dot(x[i],w) + b - y[i]
        for j in range(n):
            dj_dw[j] = dj_dw[j] + err * x[i,j]
        dj_db += err
    return dj_dw/m,dj_db/m

In [20]:
def gradient_descent(x,y,w_in,b_in,num_iter,alpha):
    w = w_in
    b = b_in
    m = x.shape[0]
    for i in range(num_iter):
        dj_dw,dj_db = compute_gradient(x,y,w,b)
        w = w - alpha * dj_dw
        b = b - alpha * dj_db
    return w,b

In [22]:
n = x_input.shape[1]
initial_w = np.zeros((n,))
initial_b = 0.
iterations = 1000
alpha = 5.0e-7

w,b = gradient_descent(x_input,y_input,initial_w,initial_b,iterations,alpha)
print(w)
print(b)

[ 0.20396569  0.00374919 -0.0112487  -0.0658614 ]
-0.0022354075309325345


In [ ]:
#Predicting the values
m = x.shape[0]
f_wb = np.zeros(m)
for i in range(m):
    f_wb[i] = np.dot(x[i],w) + b

for i in range(m):
    print(f"Actual Output : {f_wb[]i}")