In [2]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
import tensorflow as tf
import numpy as np
from sklearn.datasets import make_blobs
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Normalization
from tensorflow.keras.losses import SparseCategoricalCrossentropy

2025-06-13 16:13:34.872811: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-06-13 16:13:34.882451: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1749811414.893717   13399 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1749811414.897046   13399 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-06-13 16:13:34.908490: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

In [4]:
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
x_train,y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0,random_state=30)
print(x_train[:5],y_train[:15])

[[ 1.55508243  0.84801682]
 [-5.33749882  1.03397255]
 [-4.09353183  0.67843096]
 [-1.35928349 -1.49568732]
 [-0.67987836  3.15016353]] [2 0 0 1 2 2 1 0 1 3 1 2 0 2 2]


In [12]:
model = Sequential(
    [
        Dense(25,activation="relu"),
        Dense(15,activation="relu"),
        Dense(4,activation="linear")
    ]
)

In [14]:
model.compile(loss=SparseCategoricalCrossentropy(from_logits=True))
model.fit(x_train,y_train,epochs=10)

Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.9597  
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3284  
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.1338  
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - loss: 0.0674
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0455  
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0459
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0360
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0306
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0309  
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0299  


In [15]:
predictions = model.predict(x_train)
print(predictions)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step
[[ -5.9272575   -4.9835954    5.0984745    0.82565737]
 [  7.628963     0.9227272   -2.072724   -10.51431   ]
 [  5.415468     1.3118099   -1.621588    -8.148969  ]
 ...
 [ -2.647762     5.3256726   -0.65340155  -2.6213045 ]
 [-14.013492    -4.934897     0.6795006   10.894613  ]
 [ -3.6793554   -4.4065804    4.545159    -1.3328159 ]]


In [20]:
for i in range(len(predictions)):
    print(f"{predictions[i]} - Category : {np.argmax(predictions[i])},{y_train[i]}")

[-5.9272575  -4.9835954   5.0984745   0.82565737] - Category : 2,2
[  7.628963    0.9227272  -2.072724  -10.51431  ] - Category : 0,0
[ 5.415468   1.3118099 -1.621588  -8.148969 ] - Category : 0,0
[-2.017628   5.145002  -0.7579684 -3.098147 ] - Category : 1,1
[-2.255549  -5.4649253  5.622793  -4.5191507] - Category : 2,2
[-6.0704927  -6.1293025   6.261301   -0.25435483] - Category : 2,2
[-2.8795593  5.959907  -0.7889763 -2.9614162] - Category : 1,1
[ 10.124277    -0.48004368  -2.131687   -12.967454  ] - Category : 0,0
[-2.2015355  5.7020197 -0.8765608 -3.4256105] - Category : 1,1
[-12.110416   -5.5681663   1.9085062   8.746575 ] - Category : 3,3
[-2.080447    3.0031252  -0.05316904 -1.3636177 ] - Category : 1,1
[-7.4275494  -7.7848997   7.76691    -0.31578627] - Category : 2,2
[  7.9640956   -3.2469885    0.74570125 -12.907418  ] - Category : 0,0
[-6.8356047 -8.936594   8.698125  -2.223391 ] - Category : 2,2
[-6.8783064  -6.182738    6.255852    0.79652715] - Category : 2,2
[  8.726418